### ISSUE TITLE
Circular dependency between base and oracle-java

### ISSUE THREAD

**Issue by pdehlke** [viafoura/deprecated-buri#114]
I'm working on cleaning up the playbooks so that they work with ansible 2.2 and beyond. Unfortunately there's a circular dependency: the base role depends on oracle-java if buri_base_java is true, but oracle-java depends on base. This is now a hard error.

My solution for my own fork is to eliminate buri_base_java and just always include oracle-java in base and eliminate oracle-java as a standalone role, but that may not be appropriate for an upstream merge.

Looking for guidance from you on how you'd proceed; I'd like to be able to have a PR and get this work merged rather than maintain my own fork in perpetuity.

Thanks
-P.

**Comment by jhohertz** [comment]
I've been looking at the same things recently, and also ran into this.

I'd just drop the base as a dependency of oracle-java, not sure why it was there.

**Comment by pdehlke** [comment]
Sounds reasonable. I have cleanup_fail, foundation, and base working with 2.2.2 right now; should have the rest of the roles validated & ported over the weekend. You can follow along in the feature/ansible2.2.2 branch of my fork if you like.
