### ISSUE TITLE
Roles for the rss-recipes app as a demo

### ISSUE THREAD

**Issue by jhohertz** [viafoura/deprecated-buri#18]
Similar to the flux capacitor demo, provision this example app.

https://github.com/Netflix/recipes-rss

The biggest challenge is bringing this one up to spec... the project currently does not generate the WAR files we will need to get it up... mostly just a build detail it looks, but we'll need to bring over some container environment stuff to the middletier code tree.

**Comment by cfregly** [comment]
recipes-rss, a fork from the first version of fluxcapacitor, is meant to run standalone - outside of a web app container.  last i heard, there were no plans to change this as netflix wanted to keep this demo as simple as possible.

that said, there's work being done to create an async Netty-based version here:  https://github.com/Netflix/recipes-rss/issues/11

not sure of the timeline.

**Comment by jhohertz** [comment]
Good to know... No big deal, I need to come up with a pattern for launching no-container stuff anyhow to be able to handle the Karyon 2.0 stuff, which also runs without a web container.

**Comment by jhohertz** [comment]
Bumping this as a priority, mostly to get the pattern for naked java apps sans-container sorted out as needed for RxNetty based stuff under Karyon 2.0.

**Comment by jhohertz** [comment]
This is now in the develop branch... the recipe makes it possible to run with just the jar file + resources from the webapp folder copied in. Makes use of a fork which contains changes to add support for running as a Daemon under jsvc.

Closing.
