### ISSUE TITLE
Use pigz on builder nodes

### ISSUE THREAD

**Issue by jhohertz** [viafoura/deprecated-buri#21]
Setup pigz on builder nodes to take over gzip function, will speed up image builds.

http://zlib.net/pigz/

**Comment by jhohertz** [comment]
Done, verified to be working. Closing.

**Comment by MarkRose** [comment]
I don't see pigz actually be called anywhere, just installed. I'm curious
how it's invoked with buri?

On 4 September 2014 11:58, Joe Hohertz notifications@github.com wrote:

> Done, verified to be working. Closing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viafoura/buri/issues/21#issuecomment-54500635.

## 

Mark Rose
Senior Developer
Viafoura | The Social Monetization Platform
mark@viafoura.com
1-844-VIAFOURA (1-844-842-3687)
Toronto | New York | Los Angeles

**Comment by jhohertz** [comment]
We're just having it stand in for gzip/gunzip so that bundler jobs and the like pick it up for now. (IE: mv /bin/gzip /bin/gzip.orig && ln -s /usr/bin/pigz /bin/gzip)

I'd much rather the tools allow an explicit switch, but not forking ec2-ami-tools to do so.
