### ISSUE TITLE
Vagrant support

### ISSUE THREAD

**Issue by jhohertz** [viafoura/deprecated-buri#25]
Having the all-in-one VM be able to be brought up with the assistance of Vagrant would go a long way to making the experience more friendly, especially to fans of said tools.

One run was made at this, and the problem with it stems from assumptions we're making about the inventory file location's relations to the group_vars. The environment concept we've introduced depends on this, but is the very thing keeping Vagrant from working right with our stuff.

**Comment by jhohertz** [comment]
With the deferring of #27, this may also get the same treatment, unless we can find some way for Vagrant to use an inventory file of our choosing, or just skip the ansible provisioner altogether.

**Comment by jhohertz** [comment]
Updates

1) The inventory file may not be the issue mainly anymore.. the main hang up, is I want to default to bridged DHCP for the vagrantfile, and there is apparently no way for a provisioner to discover the IP of the VM launched,  which seems... odd. Like I _must_ be missing something, but I can't find hide nor hair of it in docs or the googles.

2) Sifting through every Vagrantfile on github with "dhcp" in it, it looks like a common workaround is to provision the dhcp interface, as well as a static host-only link which is what Vagrant will actually talk on, and we can hardcode some IPs  for it. :frowning: 

I'll try that in the day(s) to come, as I'd really like to be able to offer the simplicity of a 'vagrant up' for people who want that in a demo.

**Comment by cfregly** [comment]
+1!

**Comment by jhohertz** [comment]
There is something that now appears to be working well enough in the develop branch.

Wondering if I even need the bridged interface as I'd originally thought... the main reason was due to not wanting to specify several dozen port mappings against the odd socks-like default interface of vbox... but the 192.168.33.10 works well enough for this... (like 3 interfaces coming up).

May try taking that out before closing.

**Comment by jhohertz** [comment]
Took out said extra network, and found this exposed an issue with the exhibitor role, where we used presence of "ec2metadata" on the path to determine if in EC2 or not... turns out vagrant box includes this... now test if we can resolve instance-data.ec2.internal in DNS to determine where we are, seems to work better.

As it now comes up fine out of the box, I am closing this item.
