### ISSUE TITLE
all-in-one-vm.sh fails, 'dict object' has no attribute 'stdout'

### ISSUE THREAD

**Issue by jordansamuels** [viafoura/deprecated-buri#31]
I'll preface this by saying: I am not an ansible expert by any means.

I'm running the buri code from 0223a14363c0a6e073880d42fded19f2299f5c3f using a VM set up per the instructions in the [README](README.md) .

When I run:

```
./all-in-one-vm.sh <IP_OF_VM>
```

I get a bunch of successful steps, and then:

```
TASK: [cassandra | Recording cassandra version for later use] *****************
<<IP_OF_VM>> ESTABLISH CONNECTION FOR USER: dev
fatal: [<IP_OF_VM>] => One or more undefined variables: 'dict object' has no attribute 'stdout'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/jsamuels/all-in-one-live.retry

<IP_OF_VM>                 : ok=36   changed=27   unreachable=1    failed=0
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

I tried googling that dict object error and ran into some possible solutions; but I'm not expert enough to see to the end of any of them.

Is there another commit that might work better to set up, or is there a fix for this?

Thanks,
Jordan

**Comment by jhohertz** [comment]
Try switching to the master branch or one of the tags. That your error happened where it did makes me wonder if you did checkout out as I was mangling some thing in the develop line re: the cassandra role. (Or try pulling changes on develop if you're feeling brave.)

I'm going to go switch the primary branch to the master so it's the default folks check out, so people don't run into instabilities when trying this out.

**Comment by jhohertz** [comment]
Will be a delay before the default branch changes for the record.

**Comment by jordansamuels** [comment]
Yes, this was exactly it.  When I use master / 'release/version_0.20-M6', it works fine.  Sorry for the confusion.  I'm closing this.

**Comment by jhohertz** [comment]
Hit this myself, it's a missing conditional in the source build. I hadn't seen it as I've been source building for the last week or so.

Thanks much for the report. I am re-opening as a reminder to mainline this (my git state is rather busy at the moment)

**Comment by jhohertz** [comment]
develop branch is long longer affected by the issue, plus another bug with binary cassandra builds was found along the way and quashed as well. Closing off.
