### ISSUE TITLE
Zero out free space on disk

### ISSUE THREAD

**Issue by inve1** [viafoura/deprecated-buri#63]
Add a task that fills up the free space on disk with zeros to achieve better compression for instance-store amis. This yields faster launch times.

The task will probably just be 

```
dd if=/dev/zero of=/zerofile
rm /zerofile
```

it will take a while so it makes sense to only do it on the base, and then the zeroed-out image will be copied and the free space will be preserved

**Comment by jhohertz** [comment]
One other possible approach, needs validation, that might be quicker....

1) Use SSD-backed EBS volumes when doing operations
2) Run fstrim <mountpoint>

And we should get zeroed free blocks in a more direct manner.

This all assumes we can trim on those volumes however, and if not, we're back to blowing up the balloon of zeros.

**Comment by MarkRose** [comment]
`dd` also runs faster if called with `bs=1M` as it produces fewer IO.

**Comment by jhohertz** [comment]
1) One cannot run fstrim on a gp2 EBS volume (confirmed with test today)

2) There is tool specifically built for this task, it's mission being to "keep images sparse". It is called zerofree, and is available in Ubuntu.

I'll add in support using that tool. It will only run by default in the case of selecting instance storage AMIs, as it doesn't serve much purpose for EBS-backed types, save for if you wanted to "clean" images. (So we'll have the option, if one wants it)

I'll probably also add an option for selecting the type of EBS to be used for image creation, as there could be just plain speed advantages to using say, GP2.

**Comment by jhohertz** [comment]
Also added buri_volume_type, which lets us target a gp2 EBS type. Provisioned IOPS probably needs another param for the iops number. Just running test on speed differences now.

**Comment by jhohertz** [comment]
Same resnap operation run for each, one standard, one GP2. Both forcing the zeroing to be done.

Note that many things could add variations to the full run number, but the time for the zeroing operation should be indicative of IO speed gains. 

Standard:
- full run: 8:46
- zeroing: 2:09

GP2:
- full run: 7:02
- zeroing: 1:52

Not an insignificant savings.

**Comment by jhohertz** [comment]
So this is done, so closing.
