### ISSUE TITLE
Apt lists not updated when installing packages

### ISSUE THREAD

**Issue by inve1** [viafoura/deprecated-buri#71]
When building the base [and possibly in other places] the apt lists don't get updated so when `base_buri/tasks/package-install-ubuntu.yml` is executed it might crash if certain packages don't exist on the mirrors anymore.
I solved this temporarily by adding update_cache=yes to that task, but there might be a better place for that

**Comment by jhohertz** [comment]
I tried specifying the always_run clause on that task, but it doesn't seem to override the when as I'd thought it might. (Actual use seems to be if you need something to run in "check mode")

One way to fix this is to add the flag you mentioned to all uses of apt module, but was hoping to have it happen once up front.

I think for now I'll just ensure both foundation and base are doing the update, any anything down the chain running into issues, it's just a sign we need to refresh the base again.

**Comment by jhohertz** [comment]
Closing
